/**
 * gen-npm-readme.ts — AGT-1313.
 *
 * `packages/cli/README.md` (what npm renders on the package page) is produced
 * from the repo-root `README.md` (what GitHub renders), not hand-maintained
 * as a second copy. The two audiences need one difference: GitHub resolves a
 * relative link against the repo tree for free; npm's package page has no
 * such tree, so every relative link has to become an absolute
 * `https://github.com/OpenThinkAi/think-cli/blob/main/<path>` URL. An
 * anchor-only link (`#some-heading`) still resolves fine on npm's own
 * rendered page, so those are left alone.
 *
 * The generated-command-table block (AGT-1311, `<!-- commands:begin -->` /
 * `<!-- commands:end -->`) is copied through verbatim — it contains no
 * relative links, and the root README is regenerated by `npm run gen:commands`
 * before this script ever runs (see the `prepack` chain in package.json), so
 * copying it here can never disagree with the root.
 *
 * Usage (from packages/cli):
 *   npm run gen:npm-readme             # regenerate packages/cli/README.md in place
 *   npm run gen:npm-readme -- --check  # exit 1 if the committed copy would change; write nothing
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// packages/cli/scripts -> repo root
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');

export const ROOT_README = path.join(REPO_ROOT, 'README.md');
export const NPM_README = path.join(REPO_ROOT, 'packages', 'cli', 'README.md');

export const GITHUB_BLOB_BASE = 'https://github.com/OpenThinkAi/think-cli/blob/main/';

export const HEADER_COMMENT = [
  '<!--',
  '  GENERATED FILE — do not hand-edit.',
  '',
  `  This is the repo root README (../../README.md), regenerated for npm's`,
  '  package page by `npm run gen:npm-readme` (packages/cli/scripts/gen-npm-readme.ts),',
  '  which runs automatically in `prepack`. Relative links are rewritten to',
  `  absolute GitHub URLs, because npm's package page has no repo tree to`,
  '  resolve them against. Edit the root README instead, then regenerate.',
  '-->',
].join('\n');

// Matches a full markdown link/image target: the "](...)" part, capturing the
// destination. Deliberately dumb (no nested-paren support) — the root README
// has no link destinations containing literal parentheses today, and a link
// that needed one would fail this test's regeneration-diff loudly rather than
// silently mis-rewrite.
const LINK_TARGET = /\]\(([^)]+)\)/g;

function isRewritable(target: string): boolean {
  if (target.startsWith('#')) return false; // anchor-only — resolves fine on npm's own page
  if (/^[a-z][a-z0-9+.-]*:/i.test(target)) return false; // already an absolute URL (http:, https:, mailto:, ...)
  return true;
}

/**
 * Rewrites every relative link/image destination in `content` to an absolute
 * GitHub blob URL, leaving anchor-only and already-absolute destinations
 * untouched. Exported (alongside isRewritable) so the drift test can assert
 * on the transform directly, not just the end-to-end file.
 */
export function rewriteRelativeLinks(content: string): string {
  return content.replace(LINK_TARGET, (match, target: string) => {
    if (!isRewritable(target)) return match;
    return `](${GITHUB_BLOB_BASE}${target})`;
  });
}

/** Builds the full generated packages/cli/README.md content from the root README. */
export function generateNpmReadme(): string {
  const rootContent = readFileSync(ROOT_README, 'utf-8');
  const rewritten = rewriteRelativeLinks(rootContent);
  return `${HEADER_COMMENT}\n\n${rewritten}`;
}

function main(): void {
  const args = process.argv.slice(2);
  const check = args.includes('--check');

  const next = generateNpmReadme();
  const relative = path.relative(REPO_ROOT, NPM_README);

  let current: string | undefined;
  try {
    current = readFileSync(NPM_README, 'utf-8');
  } catch {
    current = undefined;
  }

  if (current === next) {
    console.log(`${relative}: already up to date`);
    return;
  }

  if (check) {
    console.error(`${relative}: out of date — run \`npm run gen:npm-readme\``);
    process.exitCode = 1;
    return;
  }

  writeFileSync(NPM_README, next);
  console.log(`${relative}: updated`);
}

// Only run when invoked directly (`tsx scripts/gen-npm-readme.ts`), not when
// imported by the drift test for its pure functions.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
