/**
 * gen-command-table.ts — AGT-1311.
 *
 * Generates the "commands" markdown table straight from the live commander
 * registry (`src/program.ts`, the same builder `src/index.ts` parses)
 * instead of a hand-maintained list, so the GitHub README, the npm README,
 * and this repo's drift test can never disagree with the CLI's actual
 * command set.
 *
 * Depth: recurses the FULL command tree — every leaf command becomes one
 * row, named as its full path (`think <noun> <verb>`, `think <noun> <verb>
 * <verb>` for a doubly-nested group). There is no depth cap; today's tree
 * bottoms out at 1 level for most noun groups (`cortex`, `daemon`, `hook`,
 * `mcp`, `config`, `subscribe`, `long-term`) and 2 for `serve creds add`.
 * A noun group's own row uses its own `.description()` alongside its
 * children's rows.
 *
 * Exclusions: a command registered with `{ hidden: true }` (commander sets
 * `_hidden`) is skipped, along with its whole subtree. A command that merely
 * *hosts* hidden options (e.g. `think sync`'s retired `-e/--episode` alias)
 * is NOT excluded — only genuinely internal commands are (today: only
 * `refresh-blocks-internal`, AGT-1306's plumbing for `think update`).
 *
 * Usage (from packages/cli):
 *   npm run gen:commands             # regenerate every README target in place (idempotent)
 *   npm run gen:commands -- --stdout # print the table markdown only; write nothing (AGT-1316 website check)
 *   npm run gen:commands -- --check  # exit 1 if any target's committed block would change; write nothing
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import type { Argument, Command } from 'commander';
import { buildProgram } from '../src/program.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// packages/cli/scripts -> repo root
const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');

export const BEGIN_MARKER = '<!-- commands:begin (generated by npm run gen:commands — do not edit) -->';
export const END_MARKER = '<!-- commands:end -->';

// Every file that carries the generated block. The AGT-1311 drift test
// covers exactly this list — add a new surface here (not only in the test)
// so the two can never drift from each other.
export const TABLE_TARGETS: readonly string[] = [
  path.join(REPO_ROOT, 'README.md'),
  path.join(REPO_ROOT, 'packages', 'cli', 'README.md'),
];

export interface CommandRow {
  path: string;
  args: string;
  description: string;
}

function isHidden(cmd: Command): boolean {
  // `_hidden` is set by commander's `addCommand(cmd, { hidden: true })` /
  // `{ noHelp: true }` but isn't part of the public typings — it's a real
  // (unprefixed-by-`#`) property, just not one commander promises to keep,
  // so the cast is confined to this one call site.
  return (cmd as unknown as { _hidden?: boolean })._hidden === true;
}

function formatArgs(cmd: Command): string {
  return cmd.registeredArguments
    .map((arg: Argument) => {
      const name = arg.variadic ? `${arg.name()}...` : arg.name();
      return arg.required ? `<${name}>` : `[${name}]`;
    })
    .join(' ');
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function collectRows(cmd: Command, prefix: readonly string[], rows: CommandRow[]): void {
  for (const sub of cmd.commands) {
    if (isHidden(sub)) continue; // skip the hidden command AND its subtree
    const fullPath = [...prefix, sub.name()];
    rows.push({
      path: fullPath.join(' '),
      args: formatArgs(sub),
      description: sub.description(),
    });
    collectRows(sub, fullPath, rows);
  }
}

/**
 * Pure function: walks the live commander registry (built fresh each call,
 * so nothing here is order-dependent on other test/script state) into the
 * flat, ordered list of visible commands. This is the single source both
 * `generateCommandTable()` (markdown) and the AGT-1311 AC4 vocabulary/length
 * test read from — one walk, two consumers, so they can't drift from the
 * registry or each other.
 */
export function getCommandRows(): CommandRow[] {
  const program = buildProgram();
  const rows: CommandRow[] = [];
  collectRows(program, ['think'], rows);
  return rows;
}

/**
 * Pure function: builds the markdown table body (no markers) from the live
 * registry. Shared by this script's file-writing mode, its `--stdout` mode,
 * and the AGT-1311 drift test — every consumer reads off this one function
 * so there is exactly one place the table can be wrong.
 */
export function generateCommandTable(): string {
  const rows = getCommandRows();

  const lines = [
    '| Command | Args | Description |',
    '| --- | --- | --- |',
    ...rows.map((r) => {
      const args = r.args ? `\`${r.args}\`` : '';
      return `| \`${r.path}\` | ${args} | ${escapeCell(r.description)} |`;
    }),
  ];
  return lines.join('\n');
}

/** The table wrapped in its generated-content markers, exactly as committed in README targets. */
export function generateBlock(): string {
  return `${BEGIN_MARKER}\n${generateCommandTable()}\n${END_MARKER}`;
}

/**
 * Replaces the marker-delimited block inside `content` with a freshly
 * generated one, leaving everything else byte-for-byte untouched. Throws if
 * the markers aren't both present, in order — callers should treat that as
 * "this file doesn't carry the generated table" rather than silently no-op.
 */
export function applyToContent(content: string): string {
  const beginIdx = content.indexOf(BEGIN_MARKER);
  const endIdx = content.indexOf(END_MARKER);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    throw new Error(
      `gen-command-table: markers not found (or out of order) — expected both "${BEGIN_MARKER}" and "${END_MARKER}"`,
    );
  }
  const before = content.slice(0, beginIdx);
  const after = content.slice(endIdx + END_MARKER.length);
  return `${before}${generateBlock()}${after}`;
}

function main(): void {
  const args = process.argv.slice(2);

  if (args.includes('--stdout')) {
    process.stdout.write(generateCommandTable() + '\n');
    return;
  }

  const check = args.includes('--check');
  let anyOutOfDate = false;

  for (const file of TABLE_TARGETS) {
    const current = readFileSync(file, 'utf-8');
    const next = applyToContent(current);
    const relative = path.relative(REPO_ROOT, file);

    if (next === current) {
      console.log(`${relative}: already up to date`);
      continue;
    }

    anyOutOfDate = true;
    if (check) {
      console.error(`${relative}: out of date — run \`npm run gen:commands\``);
    } else {
      writeFileSync(file, next);
      console.log(`${relative}: updated`);
    }
  }

  if (check && anyOutOfDate) {
    process.exitCode = 1;
  }
}

// Only run when invoked directly (`tsx scripts/gen-command-table.ts`), not
// when imported by the drift test for its pure functions.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
